# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 6613
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  application:
    name: ${APPLICATION_NAME:consumer}
  profiles:
    active: eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

logging:
  level:
    # feign调用所在的包
    com.github.lybgeek.api.feign: debug


feign:
  client:
    config:
      default:
        # 开启feign记录请求和响应的标题、正文和元数据
        loggerLevel: FULL
        connect-timeout: 5000
        read-timeout: 20000
lybgeek:
  gateWayUrl: localhost:8000
